name: Update Dockerfile and push in repo

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'Dockerfile7.2.tpl'
      - 'update.sh'
      - 'docker-entrypoint.sh'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: update and push
        run: |
          ./update.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "auto update"
          git push
